#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0a9 on Mon Dec  4 01:01:39 2017
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.encryption_status_label = wx.StaticText(self, wx.ID_ANY, "Encryption status: ")
        self.encryption_status = wx.StaticText(self, wx.ID_ANY, "No files")
        self.connection_status_label = wx.StaticText(self, wx.ID_ANY, "Connected to: ")
        self.connection_status = wx.StaticText(self, wx.ID_ANY, "No Connection")
        self.files_list_label = wx.StaticText(self, wx.ID_ANY, "Protected Files:")
        self.files_list_box = wx.ListBox(self, wx.ID_ANY, choices=["Nudes"], style=wx.LB_EXTENDED | wx.LB_NEEDED_SB | wx.LB_SORT)
        self.quit_button = wx.Button(self, wx.ID_ANY, "Quit")
        self.add_file_button = wx.Button(self, wx.ID_ANY, "Add File/Folder...")
        self.remove_file_button = wx.Button(self, wx.ID_ANY, "Remove selected")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.exit, self.quit_button)
        self.Bind(wx.EVT_BUTTON, self.add_file, self.add_file_button)
        self.Bind(wx.EVT_BUTTON, self.remove_file, self.remove_file_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Secure PC")
        self.files_list_box.SetSelection(0)
        self.remove_file_button.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer = wx.BoxSizer(wx.VERTICAL)
        button_sizer = wx.BoxSizer(wx.HORIZONTAL)
        file_list_sizer = wx.BoxSizer(wx.HORIZONTAL)
        connection_sizer = wx.BoxSizer(wx.HORIZONTAL)
        encryption_status_sizer = wx.BoxSizer(wx.HORIZONTAL)
        encryption_status_sizer.Add(self.encryption_status_label, 0, 0, 0)
        encryption_status_sizer.Add(self.encryption_status, 0, 0, 0)
        sizer.Add(encryption_status_sizer, 1, 0, 0)
        connection_sizer.Add(self.connection_status_label, 0, 0, 0)
        connection_sizer.Add(self.connection_status, 0, 0, 0)
        sizer.Add(connection_sizer, 1, 0, 0)
        file_list_sizer.Add(self.files_list_label, 0, 0, 0)
        file_list_sizer.Add(self.files_list_box, 0, wx.ALIGN_RIGHT | wx.EXPAND | wx.SHAPED, 0)
        sizer.Add(file_list_sizer, 1, wx.ALIGN_RIGHT | wx.EXPAND, 0)
        button_sizer.Add(self.quit_button, 0, 0, 0)
        button_sizer.Add(self.add_file_button, 0, 0, 0)
        button_sizer.Add(self.remove_file_button, 0, 0, 0)
        sizer.Add(button_sizer, 1, 0, 0)
        self.SetSizer(sizer)
        sizer.Fit(self)
        self.Layout()
        # end wxGlade

    def exit(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'exit' not implemented!")
        event.Skip()

    def add_file(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'add_file' not implemented!")
        event.Skip()

    def remove_file(self, event):  # wxGlade: MainFrame.<event_handler>
        print("Event handler 'remove_file' not implemented!")
        event.Skip()

# end of class MainFrame

