#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0a9 on Mon Dec  4 01:01:39 2017
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

class QRDialog(wx.Dialog):
    def __init__(self, qr, *args, **kwds):
        image = wx.Image(*qr.size)
        image.SetData(qr.convert('RGB').tobytes())
        # begin wxGlade: QRDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)

        self.__set_properties()
        # self.__do_layout()
        # end wxGlade
        self.__do_layout(image)

    def __set_properties(self):
        # begin wxGlade: QRDialog.__set_properties
        self.SetTitle("Please scan this with your phone")
        # end wxGlade

    def __do_layout(self, image):
        # begin wxGlade: QRDialog.__do_layout
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        qr_bitmap = wx.StaticBitmap(self, wx.ID_ANY, image.ConvertToBitmap(), style=wx.FULL_REPAINT_ON_RESIZE)
        sizer_3.Add(qr_bitmap, 0, wx.EXPAND | wx.SHAPED, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        self.Layout()
        # end wxGlade
# end of class QRDialog
