#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0a9 on Mon Dec  4 01:01:39 2017
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

class WelcomeDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: WelcomeDialog.__init__
        wx.Dialog.__init__(self, *args, **kwds)
        self.welcome_text = wx.StaticText(self, wx.ID_ANY, "Welcome to SecurePC (name pending)!")
        self.quit_button = wx.Button(self, wx.ID_ANY, "Quit")
        self.previous_button = wx.Button(self, wx.ID_ANY, "Previous")
        self.next_button = wx.Button(self, wx.ID_ANY, "Next")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: WelcomeDialog.__set_properties
        self.SetTitle("Welcome to Secure PC")
        self.previous_button.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: WelcomeDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.welcome_text, 0, 0, 0)
        sizer_2.Add(self.quit_button, 0, 0, 0)
        sizer_2.Add(self.previous_button, 0, 0, 0)
        sizer_2.Add(self.next_button, 0, 0, 0)
        sizer_1.Add(sizer_2, 1, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade
# end of class WelcomeDialog
